### ISSUE TITLE
Can you add an option to use scalajs-react with this framework, instead of Slinky?

### ISSUE THREAD

**Issue by NightMachinary** [shadaj/create-react-scala-app.g8#4]
I am new to web development, and Slinky is too much bleeding edge for me. I prefer using the more popular scalajs-react library. But this template is fantastic! I can already add scalajs-react to it and use it fine, but I don't want the Slinky dependencies cluttering the project.
In particular, the only thing I need from Slinky is hot-reloading. It'd be awesome if that part could be refactored out of Slinky! It might become quite popular!

**Comment by shadaj** [comment]
Unfortunately, hot loading will only work with Slinky applications because the custom Reader/Writer setup is required to make it work.

It's actually not possible to hot reload Scala.js apps with other libraries, since Scala.js objects aren't portable across instances of your code. The Reader/Writer part of Slinky makes it possible to instead  store just the data contained inside your objects and "rehydrate" new instances of Scala.js objects when new versions of code are launched. You can see https://slinky.shadaj.me/docs/technical-overview/ for a more detailed explanation.
